import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: "#64C8FF",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gray-950 text-white ${poppins.className}`} suppressHydrationWarning={true}>
        {children}
        </body>
    </html>
  )
}
